services:
  qa-tooling-fhir-r4:
    build: .
    image: ghcr.io/ardontoonstra/qa-tooling-fhir-r4
    container_name: qa-tooling-fhir-r4
    volumes:
      - type: bind
        source: .
        target: /repo
        read_only: true
    environment:
      - MENU_PORT=9000
    ports:
      - 9000:9000
